### ISSUE TITLE
i18next::backendConnector: No backend was added via i18next.use. Will not load resources.

### ISSUE THREAD

**Issue by Razzwan** [locize/i18next-locize-backend#298]
I following this example: https://github.com/i18next/react-i18next/tree/master/example/locize and have project which I can access on https://www.locize.io, but I always get this error:
```
i18next::backendConnector: No backend was added via i18next.use. Will not load resources.
```

**Comment by jamuhl** [comment]
the warning says you did not add one.

are you using typescript? if so check the imports are done correctly.

**Comment by jamuhl** [comment]
Not sure - i do not understand typescript, but es modules `import * as Backend from 'i18next-locize-backend'` is wrong -> has to be `import Backend from 'i18next-locize-backend'` or if using `import * as Backend from 'i18next-locize-backend'` it must be the default named export:

```js
i18next
	.use(Backend.default)
```

**Comment by michivogler** [comment]
Ok, I think I figured it out. You were right about the import. 

The problem is the export in the type definition which is actually no default export. If I change `export = I18NextLocizeBackend`  to `export default I18NextLocizeBackend` the import `import Backend from 'i18next-locize-backend'` works and the backend gets loaded correctly.

https://github.com/locize/i18next-locize-backend/blob/master/index.d.ts#L101

**Comment by jamuhl** [comment]
let me change that and publish a patch

**Comment by jamuhl** [comment]
published that update in i18next-locize-backend@1.7.1

**Comment by michivogler** [comment]
That was fast, thanks!

**Comment by jamuhl** [comment]
that's the level of service we like to provide with https://locize.com
